version: '3.8'

services:
  sqlite-admin:
    image: coleifer/sqlite-web
    command: >
      sh -c "sqlite3 /db/database.db < /docker-entrypoint-initdb.d/init.sql && sqlite_web /db/database.db -H 0.0.0.0 -p 8080"
    volumes:
      - shared-db:/db
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8080:8080"

  squid-proxy:
    build:
      context: ./squid
    container_name: squid-proxy
    volumes:
      - shared-db:/etc/squid/auth
      - cert-dir:/etc/squid/certs/
    ports:
      - "13129:3129"
    depends_on:
      - sqlite-admin

volumes:
  shared-db:
  shared-dir:

