version: '3.8'

services:
  sqlite-admin:
    build:
      context: ./sqlite
    container_name: sqlite-admin
    volumes:
      - shared-db:/db
    ports:
      - "8080:8080"

  squid-proxy:
    build:
      context: ./squid
    container_name: squid-proxy
    volumes:
      - shared-db:/etc/squid/auth
    ports:
      - "3128:3128"
    depends_on:
      - sqlite-admin

volumes:
  shared-db:

